version: '3.1'
services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    #类似 Docker 中的 --add-host 参数 ，https://ipaddress.com/website/api.tmdb.org
    extra_hosts:
      - "api.themoviedb.org:52.85.151.18"
      - "api.themoviedb.org:52.85.151.24"
      - "api.themoviedb.org:52.85.151.28"
      - "api.themoviedb.org:52.85.151.48"
      - "api.Tmdb.org:18.160.37.15"
      - "api.Tmdb.org:18.160.37.20"
      - "api.Tmdb.org:18.160.37.47"
      - "api.Tmdb.org:18.160.37.81"
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./jellyfin/config:/config
      - ./jellyfin/cache:/cache
      - ./jellyfin/media:/media
      - D:/jellyfin-films:/jellyfin-films
    ports:
      - 8096:8096
      - 8920:8920
      - 7359:7359/udp
      - 1900:1900/udp
    restart: always