version: '3.1'

services:
  app:
    image: nextcloud
    container_name: nextcloud
    restart: always
    ports:
      - 12345:80
    environment:
      - PHP_UPLOAD_LIMIT=5000M
      - PHP_MEMORY_LIMIT=5000M
      - REDIS_HOST=192.168.0.107
      - REDIS_HOST_PORT=6379
      - REDIS_HOST_PASSWORD=PASSWORD
    volumes:
      - ./nextcloud/data:/var/www/html/data
      - ./nextcloud/config:/var/www/html/config